apps/article/models.py
from datetime import datetime

from exts import db


class Article_category(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    type_name = db.Column(db.String(20), nullable=False)
    articles = db.relationship('Article', backref='article_category')


class Article(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(50), nullable=False)
    content = db.Column(db.Text, nullable=False)
    pdatetime = db.Column(db.DateTime, default=datetime.now)
    click_num = db.Column(db.Integer, default=0)
    save_num = db.Column(db.Integer, default=0)
    love_num = db.Column(db.Integer, default=0)
    # 外键  一对多 同步到数据库的关系
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    category_id = db.Column(db.Integer, db.ForeignKey('article_category.id'), nullable=False)
    comments = db.relationship('Comment', backref='article')


class Comment(db.Model):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    comment = db.Column(db.String(150), nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    article_id = db.Column(db.Integer, db.ForeignKey('article.id'), nullable=False)
    cdatetime = db.Column(db.DateTime, default=datetime.now)

    def __str__(self):
        return self.comment

apps/article/views.py
from flask import Blueprint, render_template, request

from apps.article.models import Article
from apps.user.models import User
from exts import db

article_bp = Blueprint('articles', __name__)


@article_bp.route('/publish', methods=['GET', 'POST'])
def publish_article():
    if request.method == 'POST':
        title = request.form.get('title')
        content = request.form.get('content')
        uid = request.form.get('uid')
        # 添加文章
        article = Article()
        article.title = title
        article.content = content
        article.user_id = uid
        db.session.add(article)
        db.session.commit()
        return 'success!!'

    else:
        users = User.query.filter(User.isdelele == False).all()
        return render_template('articles/add_article.html', users=users)


@article_bp.route('/all')
def all_article():
    articles = Article.query.all()
    return render_template('articles/all.html', articles=articles)


@article_bp.route('/all1')
def all_article1():
    id = request.args.get('id')
    user = User.query.get(id)
    return render_template('articles/all1.html', user=user)

templates/articles/add_article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加文章</title>
</head>
<body>
<form action="{{ url_for('articles.publish_article') }}" method="post">
    <p><input type="text" name="title" placeholder="文章标题"></p>
    <p><textarea name="content" id="" cols="30" rows="10" placeholder="输入文章内容" ></textarea></p>
    <p>
        用户:
        <select name="uid" id="">
            <option value="0">请选择用户</option>
            {% for user in users %}
                <option value="{{ user.id }}">{{ user.username }}</option>
            {% endfor %}
        </select>
    </p>
    <p><input type="submit" value="添加文章"></p>
</form>
</body>
</html>

templates/articles/all.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        #container{
            border: 1px solid brown;
            margin-bottom: 10px;
            padding: 5px;
        }
    </style>
</head>
<body>
{% for article in articles %}
    <div id="container">
        <p>
        <h3>{{ article.title }}</h3>
        <div>作者:{{ article.user.username }}</div>
        </p>
    <p>
        {{ article.content }}
    </p>
    <div>{{ article.pdatetime }}</div>
    </div>
{% endfor %}


<p></p>
</body>
</html>

templates/articles/all1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{# 根据用户获取文章们 #}
{% for article in user.articles %}
    <div id="container">
        <p>
        <h3>{{ article.title }}</h3>
        <div>作者:{{ article.user.username }}</div>
        </p>
        <p>
            {{ article.content }}
        </p>
        <div>{{ article.pdatetime }}</div>
    </div>
{% endfor %}

</body>
</html>