apps/user/models.py
from datetime import datetime

from exts import db


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(15), nullable=False)
    password = db.Column(db.String(164), nullable=False)
    phone = db.Column(db.String(11), unique=True, nullable=False)
    email = db.Column(db.String(30))
    icon = db.Column(db.String(100))
    isdelele = db.Column(db.Boolean, default=False)
    rdatetime = db.Column(db.DateTime, default=datetime.now)
    # 增加一个字段  relationship不是数据库层面，不需要迁移  是view和templates层面的
    articles = db.relationship('Article', backref='user')
    photos = db.relationship('Photo', backref='user')
    comments = db.relationship('Comment', backref='user')
    aboutme = db.relationship('AboutMe', backref='user')
    messages = db.relationship('MessageBoard', backref='user')

    def __str__(self):
        return self.username


class Photo(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    photo_name = db.Column(db.String(150), nullable=False)
    photo_datetime = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

    def __str__(self):
        return self.photo_name


class AboutMe(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.BLOB, nullable=False)
    use_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    pdatetime = db.Column(db.DateTime, default=datetime.now)

    def __str__(self):
        return self.content


class MessageBoard(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    content = db.Column(db.String(255), nullable=False)
    mdatetime = db.Column(db.DateTime, default=datetime.now)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

apps/user/views.py
import hashlib

from flask import Blueprint, render_template, request, redirect, url_for
from sqlalchemy import or_, and_, not_

from apps.user.models import User
from exts import db

user_bp = Blueprint('user', __name__)


# 注册
@user_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        repassword = request.form.get('repassword')
        phone = request.form.get('phone')
        email = request.form.get('emil')
        if password == repassword:
            users = User.query.filter(User.phone == phone)
            for user in users:
                if user.phone == phone:
                    return render_template('user/register.html', msg='号码已存在')
            user = User()
            user.username = username
            user.password = hashlib.sha256(password.encode('utf-8')).hexdigest()
            user.phone = phone
            user.email = email
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('user.user_center'))
        else:
            return '密码不同'

    return render_template('user/register.html')


# 用户中心
@user_bp.route('/')
def user_center():
    # 查询数据库中的数据
    users = User.query.filter(User.isdelele == False).all()  # select * from user
    print(users)
    return render_template('user/center.html', users=users)


# 用户登录
@user_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form.get('username')
        password = request.form.get('password')
        # 关键部分 select * from user where username='xxx'
        new_password = hashlib.sha256(password.encode('utf-8')).hexdigest()
        user_list = User.query.filter_by(username=username)
        print(user_list)
        for u in user_list:
            if u.password == new_password:
                return '用户登录成功'
        return render_template('user/login.html', msg='用户名或密码错误')
    return render_template('user/login.html')


# 用户搜索
@user_bp.route('/search', methods=['GET', 'POST'])
def search():
    # if request.method == 'get':
    keyword = request.args.get('search')
    users = User.query.filter(or_(User.username.contains(keyword), User.phone.contains(keyword)))
    return render_template('user/center.html', users=users)


# 用户删除
@user_bp.route('/delete')
def delete():
    # 获取用户ID
    id = request.args.get('id')
    # 逻辑删除 -----------》其实就是更新
    # # 获取该id用户
    # user = User.query.get(id)
    # # 逻辑删除
    # user.isdelele = True
    # # 提交
    # db.session.commit()

    # 物理删除
    user = User.query.get(id)
    # 加到缓存中
    db.session.delete(user)
    # 提交
    db.session.commit()
    return redirect(url_for('user.user_center'))


# 用户信息更新
@user_bp.route('/update', methods=['GET', 'POST'])
def update():
    if request.method == 'POST':
        username = request.form.get('username')
        phone = request.form.get('phone')
        id = request.form.get('id')
        user = User.query.get(id)
        user.username = username
        user.phone = phone
        db.session.commit()
        return redirect(url_for('user.user_center'))
    else:
        id = request.args.get('id')
        user = User.query.get(id)
        return render_template('user/update.html', user=user)


@user_bp.route('/test')
def test():
    username = request.args.get('username')
    user = User.query.filter_by(username=username).first()
    print(user.username, user.rdatetime)
    # 无last() 属性
    # user = User.query.filter_by(username=username).all()
    print(user.username, user.rdatetime)
    return 'test'


@user_bp.route('/select')
def user_select():
    # 根据主键查询用户部分
    user = User.query.get(1)
    # 注意和fileter_by 的区别
    # user = User.query.filter(User.username=='bing').all()  #all()   first()   user[:]
    # user = User.query.filter(User.username.startswith('b')).all()
    # user = User.query.filter(User.username.contains('b')).all()
    # user = User.query.filter(or_(User.username.like('b%'), User.username.contains('i'))).all()
    # user = User.query.filter(and_(User.rdatetime.__lt__('2021-09-06 22:05:58'), User.username.contains('b'))).all()
    # user = User.query.filter(and_(User.rdatetime < '2021-09-06 22:05:58', User.username.contains('b'))).all()
    # user = User.query.filter(not_( User.username.contains('b'))).all()
    # user = User.query.filter(User.phone.in_(['154254','15736980819'])).all()
    # user = User.query.order_by('rdatetime').all()
    # user = User.query.filter(User.username.contains('b')).order_by('rdatetime').all()
    # user = User.query.order_by(-User.rdatetime).all()
    # user = User.query.filter(User.username.contains('b')).order_by(-User.rdatetime).all()
    # user = User.query.order_by(-User.rdatetime).limit(2).all()
    user = User.query.order_by(-User.rdatetime).offset(2).limit(2).all()
    return render_template('user/select.html', user=user)

templates/user/aboutme.html
{% extends 'base.html' %}
{% block title %}
    个人信息
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            height: 800px;
            background-color: darkseagreen;
            margin: 0 auto;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        {% if content %}
            {% for cont in content %}
                {{ cont.content | cdecode | safe }}
            {% endfor %}
        {% else %}
            没有个人介绍哦！！！！！！
        {% endif %}

    </div>


{% endblock %}

templates/user/board.html
{% extends 'base.html' %}
{% block title %}
    文章详情
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            height: 1000px;
            margin: 0 auto;
        }

        #container p {
            overflow: auto;
        {#height: 20px;#}
        }


        #comment {
            margin-top: 50px;
            width: 900px;
        }

        #commit_item {
            width: 900px;
        }

        .item {
            width: 900px;
            height: 80px;
            background-color: #00feff;
            margin-bottom: 15px;
            border: 1px solid gray;
        }

        #item-left {
            float: left;
        }

        #item_right {
            float: right;
        }

    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
    <h3>用户留言:</h3>
        <div id="comment">
            <div>
                <form action="{{ url_for('user.show_board') }}" method="post">
                    <p>
                        <textarea name="content" id="" cols="120" rows="10"></textarea>
                    </p>
                    <p>
                        <input type="submit" value="发表留言" class="btn btn-info">
                    </p>
                </form>
            </div>
            <div id="commit_item">
                {% if messages.items %}
                    {% for message in messages.items %}
                        <div class="item">
                            <div id="item-left">
                                <img src="
                                        {% if message.user.icon %}{{ url_for('static', filename=message.user.icon) }}{% else %}{{ url_for('static', filename='Images/touxiang.jpg') }}{% endif %}"
                                     alt="" height="50px" width="70px">
                                {#                            <img src="{{ url_for('static', filename='images/touxiang.jpg') }}" alt="" height="50px" width="70px">#}
                            </div>
                            <div id="item_right">
                                <p>
                                    {% if message.user_id %}
                                        <span>{{ message.user.username }}</span>
                                    {% else %}
                                         <span>匿名用户</span>
                                    {% endif %}
                                    <span>{{ message.mdatetime }}</span>
                                </p>
                                <p>
                                    {{ message.content }}
                                </p>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <div> 还没有任何留言！！！</div>
                {% endif %}
                <nav aria-label="...">
                    <ul class="pager">
                        <li class="previous {% if not messages.has_prev %} disabled {% endif %}"><a
                                href="{{ url_for('user.show_board') }}?page={{ messages.prev_num }}"><span
                                aria-hidden="true">&larr;</span> 上一页</a></li>
                        <li class="next  {% if not messages.has_next %} disabled {% endif %}"><a
                                href="{{ url_for('user.show_board') }}?page={{ messages.next_num }}">下一页
                            <span
                                    aria-hidden="true">&rarr;</span></a></li>
                    </ul>
                </nav>
            </div>
        </div>
{% endblock %}

templates/user/center.html
{% extends 'base.html' %}
{% block title %}
    用户中心
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 1200px;
            margin: 0 auto;
        }

        .logintab h3 {
            padding-right: 170px;
            text-align: center;
            margin-bottom: 50px;
        }

        #container form {
            margin: 0 auto;
        }

        #tab {
            font-size: 20px;
            text-align: left;
            padding-left: 170px;
            margin-bottom: 50px;
        }

        #tab span {
            display: inline;
            width: 1000px;
            text-align: center;
            cursor: default;
        }

        #tips {
            color: red;
            font-size: 14px;
        }


    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">
    <div id="tab">
        <span>用户信息修改</span> | <span>发表文章</span> | <span>个人相册</span> | <span>个人留言</span> | <span>填写介绍</span>
    </div>
    <div class="logintab">
        <p id="tips">{{ msg }}</p>
        {#            如果是文件上传 表单中必须添加enctype#}
        <form class="form-horizontal" method="post" action="{{ url_for('user.user_change') }}"
              enctype="multipart/form-data">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-6 ">
                    <input type="text" class="form-control" id="inputUsername" placeholder="姓名"
                           name="username" value="{{ g.user.username }}">
                </div>
            </div>
            {#            user 和 g.user 一样   都是user对象  g传到这个页面还有作用#}
            <div class="form-group">
                <div class="col-md-offset-2 col-md-6 ">
                    <input type="text" class="form-control" id="inputPhone" placeholder="手机号"
                           name="phone" value="{{ user.phone }}"> <span></span>
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-6">
                    <input type="email" class="form-control" id="inputEamil" placeholder="邮箱" name="email"
                           value="{{ g.user.email }}">
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-6">
                    <input type="file" class="form-control" id="inputFile" placeholder="头像" name="icon">
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-3">
                    <p>
                        <img src="{% if user.icon %} {{ url_for('static', filename=user.icon) }}
                                {% else %}{{ url_for('static', filename='Images/touxiang.jpg') }} {% endif %}" alt=""
                             height="80px" width="70px">
                    </p>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary col-md-3">修&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;改
                    </button>
                    {#                        <button type="reset" class="btn btn-primary col-md-3">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置#}
                    {#                        </button>#}
                </div>
            </div>
        </form>
    </div>
    <div class="logintab">
        {#            <form class="form-horizontal" method="post" action="{{ url_for('article.publish_article') }}?id={{ user.id }}">#}
        <form class="form-horizontal" method="post" action="{{ url_for('article.publish_article') }}">
            <div class="form-group">
                <div class="col-md-offset-2 col-md-6 ">
                    <input type="text" class="form-control" id="inputTitle" placeholder="请输入文章标题"
                           name="title">
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-4">
                    <select name="type" id="">
                        <option value="0">选择文章的类型</option>
                        {% for type in types %}
                            <option value="{{ type.id }}">{{ type.type_name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-6">
                    <textarea name="content" class="mytextarea" cols="30" rows="10"></textarea>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-6">
                    <button type="submit" class="btn btn-primary col-md-3">发表文章
                    </button>
                </div>
            </div>
        </form>
    </div>
    <div class="logintab">
        <form class="form-horizontal" method="post" action="{{ url_for('user.upload_photo') }}"
              enctype="multipart/form-data">
            <div class="form-group">
                <div class=" col-md-offset-2 col-md-4">
                    <input type="file" class="form-control" id="inputPhoto" placeholder="图片" name="photo">
                </div>
                <div class="col-md-3">
                    <input type="submit" id="btnUp" class="btn btn-primary" value="上传图片">
                </div>
            </div>
        </form>
        <h3>我的相册</h3>
        <div class="row">
            {% for photo in photos %}
                <div class="col-xs-6 col-sm-4">
                    <img src="http://qzh2je0r2.hn-bkt.clouddn.com/{{ photo.photo_name }}"
                         alt="" class="img-rounded  image" height="160px" width="140px">
                    <div class="row">
                        <div class="col-md-offset-1 col-md-4">
                            <button type="button" class="btn btn-info btn-xs photo-del" tag="{{ photo.id }}">删除
                            </button>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="logintab">
        <div id="comment">
                {% if messages %}
                    <table class="table table-hover">
                        <tr>
                            <th>序号</th>
                            <th>留言</th>
                            <th>时间</th>
                            <th>操作</th>
                        </tr>
                        {% for message in messages %}
                            <tr>
                                <td>{{ loop.index }}</td>
                                <td>{{ message.content }}</td>
                                <td>{{ message.mdatetime }}</td>
                                <td><a href="{{ url_for('user.delete_board') }}?mid={{ message.id }}">删除留言</a></td>
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <div> 还没有任何留言！！！</div>
                {% endif %}
        </div>
    </div>
    <div class="logintab">
            <form class="form-horizontal" method="post" action="{{ url_for('user.about_me') }}">
                <div class="form-group">
                    <div class=" col-md-offset-2 col-md-6">
                        <textarea name="content" class="mytextarea" cols="30" rows="10"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-6">
                        <button type="submit" class="btn btn-primary col-md-3">提交</button>
                    </div>
                </div>
            </form>
        </div>

{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{ url_for('static', filename='tinymce/tinymce.min.js') }}" type="text/javascript"></script>
    <script src="{{ url_for('static', filename='js/center.js') }}" type="text/javascript"></script>
    {#    <script>#}
    {#        $(function () {#}
    {#            // 显示  隐藏 登陆方式  先隐藏 后展示#}
    {#            $(".logintab").hide();#}
    {#            $(".logintab").first().show();#}
    {#            $("#tab span").each(function (i) {#}
    {#                $(this).click(function () {#}
    {#                    $(".logintab").hide();#}
    {#                    $(".logintab").eq(i).show();#}
    {#                })#}
    {#            });#}
    {#        });#}
    {#        tinymce.init({#}
    {#            selector: '.mytextarea',#}
    {#            height: 400,#}
    {#            plugins: "quickbars emoticons",#}
    {#            inline: false,#}
    {#            toolbar: true,#}
    {#            menubar: true,#}
    {#            quickbars_selection_toolbar: 'bold italic | link h2 h3 blockquote',#}
    {#            quickbars_insert_toorbar: 'quickimage quicktable',#}
    {#        })#}
    {#        $('#inputPhone').blur(function () {#}
    {#            let phone = $(this).val();#}
    {#            let span_ele = $(this).next('span');#}
    {#            if (phone.length == 11) {#}
    {#                span_ele.text('');#}
    {#                // {#jqery ajax  get请求#}
    {#                $.get('/user/checkphone', {phone: phone}, function (data) {#}
    {#                        // {#console.log(data)#}
    {#                        if (data.code != 200) {#}
    {#                            span_ele.css({"color": "#ff0011", "font-size": "12px"});#}
    {#                            span_ele.text(data.msg);#}
    {#                        }#}
    {#                    }#}
    {#                )#}
    {#            } else {#}
    {#                span_ele.css({"color": "#ff0011", "font-size": "12px"});#}
    {#                span_ele.text('手机格式错误');#}
    {#            }#}
    {#        });#}
    {#    </script>#}
{% endblock %}

templates/user/index.html
{% extends 'base.html' %}
{% block title %}
    博客首页
{% endblock %}

{% block styles %}
    {{ super() }}
    <style>
        #container {
            width: 1000px;
            height: 1000px;
            margin: 0 auto;
        }

        .article {
            width: 900px;
            background-color: darkseagreen;
        {#height: 100px;#} margin-bottom: 20px;
            border-bottom: 1px solid gray;
        }

        .article div span {
            margin-right: 10px;
            padding-right: 20px;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        {#    直接获取文章 不进行分页#}
        {#        {% for articles in articles %}#}
        {#            <div class="articles">#}
        {#                <h4><a href="">{{ articles.title }}</a></h4>#}
        {#                <p>#}
        {#                    <span>作者:{{ articles.user.username }}</span>#}
        {#                    <br>#}
        {#                    通过过滤器先将二进编码出来出来    然后 用safe 不讲标签进行转义   让浏览器进行解析#}
        {#                    <span>{{ articles.content | cdecode | safe }}</span>#}
        {#                </p>#}
        {#                <div>#}
        {#                    <span style="margin-left: 0">发布时间: {{ articles.pdatetime }}</span>#}
        {#                    <span>收藏:{{ articles.save_num }}</span><span>点击量:{{ articles.click_num }}</span>#}
        {#                </div>#}
        {#            </div>#}
        {#        {% endfor %}#}

        {#    达到分页的效果   以下代码可以实现#}
        {% for article in pagination.items %}
            <div class="article">
                <h4><a href="{{ url_for('article.article_detail') }}?aid={{ article.id }}">{{ article.title }}</a></h4>
                <p>
                    <span>作者:{{ article.user.username }}</span>
                    <br>
                    {#                    通过过滤器先将二进编码出来出来    然后 用safe 不讲标签进行转义   让浏览器进行解析#}
                    <span>{{ article.content | cdecode | safe }}</span>
                </p>
                <div>
                    <span style="margin-left: 0">发布时间: {{ article.pdatetime }}</span>
                    <span>收藏:{{ article.save_num }}</span><span>点击量:{{ article.click_num }}</span>
                </div>
            </div>
        {% endfor %}
        <nav aria-label="..." class=" col-md-offset-4">
            <ul class="pagination">
{#            pagination.has_prev  判断是否存在上一页  如果存在可以点击  否则不可以点击#}
                <li {% if not pagination.has_prev %} class="disabled" {% endif %}><a
                        href="{{ url_for('user.index') }}?page={{ pagination.prev_num }}" aria-label="Previous"><span
                        aria-hidden="true">&laquo;</span></a></li>
                {% for page_num in range(1, pagination.pages + 1) %}
                    <li {% if pagination.page==page_num %}  class="active" {% endif %}><a
                            href="{{ url_for('user.index') }}?page={{ page_num }}">{{ page_num }} <span class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}
{#                pagination.has_next  判断是否存在下一页  如果存在下一页 可以点击  否则不可以点击#}
                <li {% if not pagination.has_next %} class="disabled" {% endif %}><a
                        href="{{ url_for('user.index') }}?page={{ pagination.next_num }}" aria-label="Next"><span
                        aria-hidden="true">&raquo;</span></a></li>
            </ul>
        </nav>
    </div>

{% endblock %}

templates/user/photos.html
{% extends 'base.html' %}
{% block title %}
    相册展示
{% endblock %}
{% block styles %}
    {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
        {#height: 1200px;#} margin: 0 auto;
            background-color: #dfe0e4;
        }
    </style>
{% endblock %}
{% block newcontent %}
    <div id="container">
        <div class="row">
            {#            {% for photo in photos %}#}
            {#                <div class="col-xs-6 col-sm-4">#}
            {#                    <img src="http://qzh2je0r2.hn-bkt.clouddn.com/{{ photo.photo_name }}"#}
            {#                         alt="" height="300px" width="300px">#}
            {#                </div>#}
            {#            {% endfor %}#}
            {% for photo in photos.items %}
                <div class="col-xs-6 col-sm-4">
                    <img src="http://qzh2je0r2.hn-bkt.clouddn.com/{{ photo.photo_name }}"
                         alt="" height="300px" width="300px">
                </div>
            {% endfor %}
        </div>
        <nav aria-label="..." class=" col-md-offset-4">
            <ul class="pagination">
                {#            pagination.has_prev  判断是否存在上一页  如果存在可以点击  否则不可以点击#}
                <li {% if not photos.has_prev %} class="disabled" {% endif %}><a
                        href="{{ url_for('user.myphoto') }}?page={{ photos.prev_num }}"
                        aria-label="Previous"><span
                        aria-hidden="true">&laquo;</span></a></li>
                {% for page_num in range(1, photos.pages + 1) %}
                    <li {% if photos.page==page_num %}  class="active" {% endif %}><a
                            href="{{ url_for('user.myphoto') }}?page={{ page_num }}">{{ page_num }} <span
                            class="sr-only">(current)</span></a>
                    </li>
                {% endfor %}
                {#                pagination.has_next  判断是否存在下一页  如果存在下一页 可以点击  否则不可以点击#}
                <li {% if not photos.has_next %} class="disabled" {% endif %}><a
                        href="{{ url_for('user.myphoto') }}?page={{ photos.next_num }}" aria-label="Next"><span
                        aria-hidden="true">&raquo;</span></a></li>
            </ul>
        </nav>
        <nav aria-label="...">
            <ul class="pager">
                <li class="previous {% if not photos.has_prev %} disabled {% endif %}"><a
                        href="{{ url_for('user.myphoto') }}?page={{ photos.prev_num }}"><span
                        aria-hidden="true">&larr;</span> Older</a></li>
                <li class="next  {% if not photos.has_next %} disabled {% endif %}"><a
                        href="{{ url_for('user.myphoto') }}?page={{ photos.next_num }}">Newer <span
                        aria-hidden="true">&rarr;</span></a></li>
            </ul>
        </nav>
    </div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% block title %}
    用户注册
{% endblock %}
{% block styles %}
     {{ super() }}
    <style>
        #container {
            padding-top: 30px;
            width: 1000px;
            height: 600px;
            margin: 0 auto;
        }

        #container h1 {
            text-align: center;
            margin-bottom: 50px;
        }

        #container form {
            margin: 0 auto;
        }
        #tab {
            font-size: 20px;
            text-align: left;
            padding-left: 170px;
            margin-bottom: 50px;
        }
        #tab span{
            display: inline;
            width: 120px;
            text-align: center;
            cursor: default;
        }
        {##container h1#}
    </style>
{% endblock %}

{% block newcontent %}
    <div id="container">

        <h1>用户注册</h1>
        <form class="form-horizontal" method="post" action="{{ url_for('user.register') }}">
            <div class="form-group">
                <label for="inputUsername" class="col-md-2 control-label">用户名</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" id="inputUsername" placeholder="username" name="username">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPassword" class="col-md-2 control-label">密码</label>
                <div class="col-md-6">
                    <input type="password" class="form-control" id="inputPassword" placeholder="password"
                           name="password">
                </div>
            </div>
            <div class="form-group">
                <label for="inputConfirm" class="col-md-2 control-label">确认密码</label>
                <div class="col-md-6">
                    <input type="password" class="form-control" id="inputConfirm" placeholder="confirm password"
                           name="repassword">
                </div>
            </div>
            <div class="form-group">
                <label for="inputPhone" class="col-md-2 control-label">手机号码</label>
                <div class="col-md-6">
                    <input type="text" class="form-control" id="inputPhone" placeholder="phone number" name="phone">
                    <span></span>
                </div>
            </div>
            <div class="form-group">
                <label for="inputEmail" class="col-md-2 control-label">邮箱</label>
                <div class="col-md-6">
                    <input type="email" class="form-control" id="inputEmail" placeholder="email" name="email">
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-md-10">
                    <button type="submit" class="btn btn-primary col-md-3">注&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;册
                    </button>
                    <button type="reset" class="btn btn-primary col-md-3">重&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;置
                    </button>
                </div>
            </div>
        </form>
    </div>

{% endblock %}
{% block scripts %}
    {{ super() }}
    <script>
        $('#inputPhone').blur(function () {
            let phone = $(this).val();
            let span_ele = $(this).next('span');
            if (phone.length == 11) {
                span_ele.text('');
                {#jqery ajax  get请求#}
                $.get('{{ url_for('user.check_phone') }}', {phone: phone}, function (data) {
                    {#console.log(data)#}
                    if (data.code != 200) {
                        span_ele.css({"color": "#ff0011", "font-size": "12px"});
                        span_ele.text(data.msg);
                    }
                });
            } else {
                span_ele.css({"color": "#ff0011", "font-size": "12px"});
                span_ele.text('手机格式错误');
            }
        })
    </script>
{% endblock %}